import './globals.css'
import type { Metadata } from 'next'




export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet' />

      </head>
      <body >{children}</body>
    </html>
  )
}
